### ISSUE TITLE
Add support for Jabra 510 MS conference device 

### ISSUE THREAD

**Issue by alexreddy78** [noisetorch/NoiseTorch#397] opened 2023-04-10 14:45 UTC
NoiseTorch shows incompatible device for Jabra 510 MS microphone. Is it some way to add support for the devide?

RGDS

Alex

**Comment by TheDukeofErl** [comment] 2023-10-10 02:20
Closing as dupe of https://github.com/noisetorch/NoiseTorch/issues/347

**Closed by TheDukeofErl** 2023-10-10 02:20 UTC
Labels: duplicate, enhancement
